export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_ID= "FETCH_CATEGORIES_ID";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const UPDATE_CATE_BY_ID = "UPDATE_CATE_BY_ID";
export const STATUS_EXC = "STATUS_EXC";

export const GET_LIST_PRODUCTS = "GET_LIST_PRODUCTS";

export const GET_LIST_BRANDS = "GET_LIST_BRANDS";
export const GET_LIST_STATUS = "GET_LIST_STATUS";
export const GET_LIST_TYPES = "GET_LIST_TYPES";

export const CREATE_PRODUCTS = "CREATE_PRODUCT";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCT";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCT";

export const CURENT_PAGE = "CURENT_PAGE";
export const LIMIT_ITEM = "LIMIT_ITEM";

export const ADMIN_SHOW_DETAIL_PRODUCT = "ADMIN_SHOW_DETAIL_PRODUCT";

export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";

export const COUNT_COMMENT_PRODUCT_ID = "COUNT_COMMENT_PRODUCT_ID";
export const COUNT_ORDER_PRODUCT_ID = "COUNT_ORDER_PRODUCT_ID";
export const COUNT_RATE_PRODUCT_ID = "COUNT_RATE_PRODUCT_ID";

export const FETCH_ORDERS_PAGE_ADMIN = "FETCH_ORDERS_PAGE_ADMIN";

// USER
export const FETCH_ALL_CATE = "FETCH_ALL_CATE";
export const FETCH_PRODUCT_CATE_ID = "FETCH_PRODUCT_CATE_ID";
export const FETCH_BRAND_CATE_ID = "FETCH_BRAND_CATE_ID";
export const FETCH_TYPE_CATE_ID = "FETCH_TYPE_CATE_ID";
export const FETCH_CATE_CATE_ID = "FETCH_CATE_CATE_ID";
export const FETCH_PRODUCT_SEARCH = "FETCH_PRODUCT_SEARCH";
export const FETCH_PRODUCT_RECENTLY = 'FETCH_PRODUCT_RECENTLY';
export const FETCH_PRODUCT_HOVER_CART = 'FETCH_PRODUCT_HOVER_CART';
export const UPDATE_URL = "UPDATE_URL";
export const GET_NUMBER_OF_CART = "GET_NUMBER_OF_CART";
export const USER_GET_PRODUCT_BY_ID = "USER_GET_PRODUCT_BY_ID";
export const USER_COUNT_COMMENT_BY_ID = "USER_COUNT_COMMENT_BY_ID";
export const USER_COUNT_RATE_BY_ID = "USER_COUNT_RATE_BY_ID";
export const USER_ORDER_PRODUCT = "USER_ORDER_PRODUCT";